version: '3'
services:
  mysql:
     image: mysql:8
     environment:
       MYSQL_ROOT_PASSWORD: 12345
       MYSQL_DATABASE: sisdb2025
     ports:
       - "3306:3306"
     networks:
       - my-network
  app:
    image: java-app-image
    build: .
    ports:
      - "8002:8002"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/sisdb2025
    networks:
      - my-network
  frontend:
    image: frontend-image
    build: ./frontend
    volumes:
      - ./frontend:/usr/share/nginx/html
    ports:
      - "5500:80"
    networks:
      - my-network
networks:
  my-network:
    driver: bridge
