version: '3'
services:
  #mysql:
    #image: mysql:8
   # environment:
  #    MYSQL_ROOT_PASSWORD: 12345
  #     MYSQL_DATABASE: taller  # Asegúrate de que la base de datos es "taller" como configuraste en tu Spring Boot
  #   ports:
  #     - "3306:3306"
  #    networks:
  #     - my-network
  app:
    image: java-app-image
    build: .
    ports:
      - "8002:8002"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3307/taller  # Cambié el nombre de la base de datos a "taller"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
