# Usa la imagen oficial de NGINX
FROM nginx:alpine

# Copia tus archivos estáticos al directorio de NGINX

COPY index.html /usr/share/nginx/html

# Expone el puerto 80 para que el contenedor sea accesible
EXPOSE 80